name: Database

on:
  - push

jobs:
  rspec-tests:
    name: RSpec test database commands
    runs-on: ubuntu-18.04
    env:
      RUBY_VERSION: 2.4
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: ${{ env.RUBY_VERSION }}
      - name: install dependencies
        run: |
          gem install rspec
      - name: build application
        run: |
          mkdir dist
          gcc-10 -o dist/database \
            main.c \
            compiler.c
      - name: run tests
        run: |
          rspec spec/database.rb
